spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_fix?characterEncoding=UTF-8&serverTimezone=JST
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: searchman
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
     naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
